# https://github.com/2b-t/realsense-ros2-docker#12-installation-from-source
# https://github.com/IntelRealSense/librealsense/blob/master/scripts/Docker/Dockerfile

# librealsense build stage
ARG BASE_IMAGE=ubuntu:20.04
FROM $BASE_IMAGE as librealsense-builder

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -qq -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    libssl-dev \
    libusb-1.0-0-dev \
    pkg-config \
    libgtk-3-dev \
    libglfw3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    curl \
    python3 \
    python3-dev \
    ca-certificates \
    vim \
    && rm -rf /var/lib/apt/lists/*

ENV LIBRS_VERSION=2.51.1

WORKDIR /usr/src

RUN curl https://codeload.github.com/IntelRealSense/librealsense/tar.gz/refs/tags/v$LIBRS_VERSION -o librealsense.tar.gz 
RUN tar -zxf librealsense.tar.gz \
    && rm librealsense.tar.gz 
RUN ln -s /usr/src/librealsense-$LIBRS_VERSION /usr/src/librealsense

RUN cd /usr/src/librealsense \
    && mkdir build && cd build \
    && cmake \
    -DCMAKE_C_FLAGS_RELEASE="${CMAKE_C_FLAGS_RELEASE} -s" \
    -DCMAKE_CXX_FLAGS_RELEASE="${CMAKE_CXX_FLAGS_RELEASE} -s" \
    -DCMAKE_INSTALL_PREFIX=/opt/librealsense \
    -DBUILD_GRAPHICAL_EXAMPLES=ON \
    -DBUILD_PYTHON_BINDINGS:bool=true \
    -DCMAKE_BUILD_TYPE=Release \
    -DPYTHON_EXECUTABLE=$(which python3) ../ \
    && make -j$(($(nproc)-1)) all \
    && make install

# ros2-foxy + realsesense-ros stage 
FROM chihiro1234567/ros2-foxy:base-1.3

ENV LIBRS_VERSION=2.51.1

SHELL ["/bin/bash", "-c"]

COPY --from=librealsense-builder /opt/librealsense /usr/local/
COPY --from=librealsense-builder /usr/lib/python3/dist-packages/pyrealsense2 /usr/lib/python3/dist-packages/pyrealsense2
COPY --from=librealsense-builder /usr/src/librealsense/wrappers/python/pyrealsense2/__init__.py  /usr/lib/python3/dist-packages/pyrealsense2
COPY --from=librealsense-builder /usr/src/librealsense-$LIBRS_VERSION/config/99-realsense-libusb.rules /etc/udev/rules.d/
ENV PYTHONPATH=${PYTHONPATH}:/usr/local/lib

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libglfw3-dev ros-${ROS_DISTRO}-rviz2 ros-${ROS_DISTRO}-v4l2-camera && \
    rm -rf /var/lib/apt/lists/*

WORKDIR ${USER_HOME}/ros2_ws/src
RUN git clone https://github.com/IntelRealSense/realsense-ros.git -b ros2-development
WORKDIR ${USER_HOME}/ros2_ws
RUN apt-get update && gosu ${USER_NAME} rosdep update && \
    gosu ${USER_NAME} rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y 
RUN echo ==== colcon build ===
RUN . /opt/ros/foxy/setup.bash && colcon build --symlink-install --cmake-clean-cache 

# docker build -t chihiro1234567/ros2-foxy:realsense251-1.4 -f Dockerfile_ros2-foxy-realsense ./
# docker run -it --rm -u $(id -u):$(id -g) chihiro1234567/ros2-humble:realsense251-1.4
#
